### ISSUE TITLE
HM-Dis-WM55 Unknown paramset

### ISSUE THREAD

**Issue by all-solutions** [hobbyquaker/node-red-contrib-ccu#10]
Unable to send something to the display. Debug shows:

```
node: RaspberryMatic
msg : string[83]
"rpc > BidCos-RF setValue ["NEQ01xxxx7:3","SUBMIT","0xF0"] < Error: Unknown paramset"
```
There is also only channel 3 available in the drop-down menu
![image](https://user-images.githubusercontent.com/17761850/43025476-40b4834e-8c72-11e8-897e-d79fda9d47ef.png)
![image](https://user-images.githubusercontent.com/17761850/43025410-ef6cfffc-8c71-11e8-9829-526f1ecd8c42.png)

**Comment by hobbyquaker** [comment]
tried to fix that in v1.1.2, but I had to do that on blind flight, got no HM-Dis-WM55 to test it...

**Comment by hobbyquaker** [comment]
The unknown paramset warning in the log will still be there, this is related to #5 - nevertheless now it should be possible to send texts/icons to the HM-Dis-WM55

**Comment by all-solutions** [comment]
Unfortunately it doesn't work. This is the command that goes aut from the display node:

> rpc > BidCos-RF setValue ["NEQ01xxxx7:3","SUBMIT","0x02,0x0A,0x12,0x41,0x75,0x73,0x11,**undefined**,0x13,0x80,0x0A,0x12,0x4F,0x66,0x66,0x65,0x6E,0x11,**undefined**,0x13,0x82,0x0A,0x12,0x49,0x6E,0x66,0x6F,0x72,0x6D,0x61,0x74,0x69,0x6F,0x6E,0x11,**undefined**,0x13,0x86,0x0A,0x12,0x20,0x11,**undefined**,0x0A,0x12,0x20

There are four "undefined" values inthere. I think this are the values from text 4&5 and icon 4&5. These won't be stored in the node configuration. After saving and reopen the node the fields are empty. Perhaps the display doesn't accept the setValue because of them.

Please also make channel 1 and 2 available in configuration. These are also used to send text to the display. Here a working example from the CCU:
![image](https://user-images.githubusercontent.com/17761850/43090219-15e4c25a-8ea7-11e8-8dfa-eb460a83b240.png)

**Comment by hobbyquaker** [comment]
Could you please clear your browsers cache and try again? I couldn't reproduce the missing values, so I guess it may be a caching issue...

**Comment by hobbyquaker** [comment]
Channel 1&2 should be available in v1.1.5

**Comment by all-solutions** [comment]
Arghhhh, missing values was really my fault. Sorry for that.

Now we just need channel 1 & 2 of the device in the node config. Channel 3 doesn't work. If I manually modify it to a "1", then the display receices an displays the values. But because it's an manual entry after reopening the config dialog, the channel settings are empty.

**Comment by hobbyquaker** [comment]
next try: v1.1.6 :-)

**Comment by all-solutions** [comment]
Great job!
- Channel 1 & 2 available
- Lines correct
![image](https://user-images.githubusercontent.com/17761850/43099392-5819414e-8ec2-11e8-92eb-a8fd01460da2.png)
Many Thanks Sebastian ![image](https://user-images.githubusercontent.com/17761850/43099589-ef5a037c-8ec2-11e8-9fc4-b25d16b97486.png)
