### ISSUE TITLE
Display node: offer possibility to set text/color/icons via msg

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/node-red-contrib-ccu#11]

**Comment by all-solutions** [comment]
Great idea, I can test it, when it's available ;-)

**Comment by hobbyquaker** [comment]
Coincidence ;-) Now available :)

**Comment by hobbyquaker** [comment]
Sorry, shouldn't publish before I really finished it ;-) Now (v1.1.10) it _should_ work. Perhaps I should order a HM-Dis-WM55, developing without being able to test is not ideal ;)

**Comment by hobbyquaker** [comment]
reopening until you confirm that it's working

**Comment by all-solutions** [comment]
Hi,
text and color works, icon not. The icon will not be displayed, if there is an icon set in the display-node this one will be displayed.
![image](https://user-images.githubusercontent.com/17761850/43148266-3d650268-8f65-11e8-927c-0fe32f293a7f.png)

BTW: you forgot icon definition :
> _**open**: '0x82',_

 ;-)

**Comment by hobbyquaker** [comment]
Thx for the bug report :) v1.1.11 is published.

**Comment by hobbyquaker** [comment]
👍
