### ISSUE TITLE
Switch Node that offers comfortable selection of cached CCU Values

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/node-red-contrib-ccu#15]
Hallo,
mal eine längere Erklärung, warum ich denke das diese Erweiterung sinvoll wäre (vielleicht gibt es auch einfach einen anderen Ansatz).

Wenn ich die Programme ähnlich der CCU aufbaue, starten die Flows mit Aktualisierung oder Änderung von Eingangs states. Diese triggern den Flow. In den CCU Programmen gibt es noch die Möglichkeit dann den Programmablauf auf Basis "nur prüfen" zu beeinflussen.

Das kann ich kompliziert machen, indem ich mir die "nur prüfen" stati persistiere und dann über einen Switch Node den Nachrichtenfluss beeinflusse.

Jetzt habe ich gesehen, das ich das gar nicht benötige, da im globalen context der stati aller Geräte bereits persistiert ist:
![image](https://user-images.githubusercontent.com/12692680/44531317-ca3a9980-a6f0-11e8-93de-678dcba53754.png)

Das kann ich auch direkt auswerten:
![image](https://user-images.githubusercontent.com/12692680/44531259-a37c6300-a6f0-11e8-8326-6147a29fe7a3.png)

Mich stört jetzt hier nur der sperrige Ausdruck `ccu-localhost.values['BidCos-RF.LEQ0000815:1.STATE'].value`

Hier wäre eine "valueSwitch" node schön, welche wie eine switch node ist, bei der die Auswahl-Felder so wie aus der value node vorhanden sind:

![image](https://user-images.githubusercontent.com/12692680/44532037-7b8dff00-a6f2-11e8-8ca9-9b3670c93c70.png)

Das stelle ich mal zur Diskussion.

**Comment by hobbyquaker** [comment]
Gute Idee, so ein Switch Node werde ich bauen. Eine evtl. mögliche andere Vorgehensweise wäre den `Combine If` Node zu nutzen, das hat imho den Vorteil das die Visualisierung des Flows klarer ersichtlich ist, ist aber denke ich Geschmackssache.

PS.: Ich würde es bevorzugen wenn wir im RedMatic Issue Tracker bleiben, dann haben wir alles Zentral an einem Platz. Bin noch am überlegen ob den Issue Tracker hier einfach abschalt.

**Comment by hobbyquaker** [comment]
So, habs mal schnell implementiert, steckt in node-red-contrib-ccu v1.2.0. Eine weitere Neuerung gibts im Config Node, dort kann man nun den Context Store auswählen in dem der Cache abgelegt wird. Der Switch Node funktioniert übrigens unabhängig vom Context, der holt sich die Werte jetzt direkt aus dem CCU Connection Node, d.h. dem ist es egal ob bzw in welchem Context Store man die Werte hat.

**Comment by Hypnos3** [comment]
Super! Danke

**Comment by hobbyquaker** [comment]
@Hypnos3 tritt das Verhalten bei Dir mit der aktuellen Version noch auf?

**Comment by Hypnos3** [comment]
Das mit der ausgegrauten interface box tritt noch auf, aber dann ist sie leer.
Tritt jetzt auch nur noch auf, wenn keine Verbindung besteht (Notebook hat WLAN verloren). 

Von mir aus ist das so ok.
