### ISSUE TITLE
RPC Event Node: No autocomplete

### ISSUE THREAD

**Issue by Sineos** [hobbyquaker/node-red-contrib-ccu#18]
The autocomplete of the RPC event node stopped working for me. For the other Nodes it is still working. Tested in Redmatic v1.2.1

**Comment by hobbyquaker** [comment]
Should be repaired with RedMatic 1.3.0 respectively node-red-contrib-ccu 1.4.1

**Comment by Sineos** [comment]
Many thanks for the quick reaction. 

I might be wrong but I think the old behavior was that the subsequent entries have been filtered according to the previous selection. For example, now all available `datapoints` for all registered devices are listed regardless of the chosen `device` or `channel`.

If I'm wrong call it a feature request ;-)

**Comment by Sineos** [comment]
And there is a second issue:
Apart from the `room`, no other select value is remembered when applying and reopening the node.

**Comment by hobbyquaker** [comment]
> Apart from the room, no other select value is remembered when applying and reopening the node.

Should be fixed in node-red-contrib-ccu 1.4.2 (you can update it via the node-red palette manager)

> I might be wrong but I think the old behavior was that the subsequent entries have been filtered according to the previous selection. ... If I'm wrong call it a feature request ;-)

I think that's a feature request, that's implemented in the `value` node, but it was never implemented in the `rpc event` node. Isn't a trivial thing, give me some time. Also raises some questions - what to do with RegExp filters? Just ignore them or do you expect them to operate on the filter also?

**Comment by Sineos** [comment]
Well, I would exclude the RegExp from the filter. If you are able to properly setup the RegExp, you anyway know what you are doing.
The filtering is a great "laziness" feature, because it saves me from looking up the data points in every case, so I would very much appreciate this.

**Comment by Sineos** [comment]
Um, I don't want to be a pain in the back, but after updating to 1.4.2 the autocomplete again stopped working :-S

**Comment by hobbyquaker** [comment]
narf :)

**Comment by hobbyquaker** [comment]
next try: v1.4.3 :)

**Comment by Sineos** [comment]
> narf :)

The same thing we do every night, @hobbyquaker - try to take over the world! 

Works 👍

**Comment by hobbyquaker** [comment]
![download](https://user-images.githubusercontent.com/2503307/44926251-1faa2280-ad51-11e8-9fb2-cfe4af80d787.jpg)
