### ISSUE TITLE
RPC Event Node: Filtering

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/node-red-contrib-ccu#19]
filter subsequent entries according to the previous selection. (was #18)

**Comment by Sineos** [comment]
Funktioniert. Vielen Dank. RegExp tut auch wie es soll (ohne Filter).

![grafik](https://user-images.githubusercontent.com/4459312/44955958-5c465d00-aebc-11e8-9340-6f859bb0a5a7.png)

Den Fehler kann man provozieren, wenn man "weiter unten" schon Einschränkungen getroffen hat und dann oberhalb dieser etwas unpassendes auswählt.
