### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by GnomiBerlin** [hobbyquaker/node-red-contrib-ccu#24]
Hello, after deploying this error comes from the node:
SyntaxError: Unexpected token  in JSON at position 29241

One side effect, which is perhaps not related to this, but since using this node-red-contrib-ccu node the docker is crashing and can not be restarted anymore. I could not see the error, as the terminal window in the Synology Docker environment is too fast away after the crash withing 10 seconds after starting the docker container.

Best Regards,
Joerg

**Comment by hobbyquaker** [comment]
hopefully the json parse error is fixed with v1.6.10

about the crashes: can't say anything helpful without logs

**Comment by GnomiBerlin** [comment]
I installed v1.6.11 and restarted Node-Red but after deploying now the error comes: SyntaxError: Unexpected token  in JSON at position 29266
crashes: you are right. If I have some data, I will add them, but currently I have no usable logs

**Comment by hobbyquaker** [comment]
@GnomiBerlin could you retry with the latest version and show me the JSON error message again?

**Comment by GnomiBerlin** [comment]
@hobbyquaker   I installed 1.6.17 and this is the error output now:
![image](https://user-images.githubusercontent.com/43815556/47483205-f8477180-d838-11e8-81d3-ac7620a0e960.png)
hopefully this helps.

**Comment by hobbyquaker** [comment]
Could you please try 1.6.18? This should fix the JSON.parse error.

**Comment by GnomiBerlin** [comment]
yes, installed and after deploy the parse error is not seen. This is the current output start...of named data points:
![image](https://user-images.githubusercontent.com/43815556/47547593-6d2cb100-d8f6-11e8-9d01-5f517e53a36f.png)

more details can be delivered if required.
