### ISSUE TITLE
get value Node: msg prop definieren

### ISSUE THREAD

**Issue by psi-4ward** [hobbyquaker/node-red-contrib-ccu#34]
Die `get Value` node setzt aktuell `payload` und überschreibt den Wert der Input-Node.
Es wäre sinnvoll, wenn man den abgerufenen Wert in einem anderen Property speichern könnte damit die original Payload erhalten bleibt. 

Bsp.: Man möchte eine Function-Node implementieren die von verschiedenen Werten abhängt.
Mit `get Value` könnte man ein die Werte nacheinander von der CCU holen und später zusammen verarbeiten.

**Comment by psi-4ward** [comment]
See PR #35

**Comment by hobbyquaker** [comment]
danke! 👍
