### ISSUE TITLE
some datapoints missing in paramsetDescriptions

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/node-red-contrib-ccu#5]
should be added to the pre-built paramsets.json

e.g. `SUBMIT` for Displays, `FREQUENCY` for wired 12/14. More?

**Comment by hobbyquaker** [comment]
@Hypnos3 - Da ich kein Wired 12/14 besitze: Könntest Du mir die Datei `/usr/local/addons/redmatic/var/ccu_paramsets.json` zuschicken (hobbyquaker@gmail.com), würde gerne die Frequency Datenpunkte hinzufügen... (Datei enthält nichts privates, keine Adressen oder sowas)

**Comment by Hypnos3** [comment]
Kann ich machen, aber erst in 2 Wochen. Bin im Urlaub.

**Comment by hobbyquaker** [comment]
@Hypnos3 ich musste das handling der paramsetDescriptions etwas umbauen, wärst Du so lieb mir nach einem Update auf RedMatic 1.2.0 bzw node-red-contrib-ccu 1.3.0 die Datei noch mal zukommen zu lassen? Sie heisst nun `/usr/local/addons/redmatic/var/ccu_paramsets_v2.json`

**Comment by hobbyquaker** [comment]
mit node-red-contrib-ccu 1.3.3 sollten die FREQUENCY und der VALUE Datenpunkt des HMW-IO-12-Sw14 nun angezeigt werden. Allerdings ist etwas Handarbeit nötig bei einem Update:

* node-red-contrib-ccu updaten
* Node-RED stoppen
* `/usr/local/addons/redmatic/var/ccu_paramsets_v2.json` löschen
